#!/bin/bash
PERL_SCRIPT=/usr/bin/fastcgi-wrapper.pl
FASTCGI_USER=www-data
FASTCGI_SOCKDIR=/var/run/www
RETVAL=0

# $FASTCGI_SOCKDIR sometimes gets removed after reboot.
if [ ! -d $FASTCGI_SOCKDIR ]
then
    mkdir -p $FASTCGI_SOCKDIR
    chown $FASTCGI_USER:$FASTCGI_USER $FASTCGI_SOCKDIR
fi

case "$1" in
    start)
      su - $FASTCGI_USER -c $PERL_SCRIPT
      RETVAL=$?
  ;;
    stop)
      killall -9 fastcgi-wrapper.pl
      RETVAL=$?
  ;;
    restart)
      killall -9 fastcgi-wrapper.pl
      su - $FASTCGI_USER -c $PERL_SCRIPT
      RETVAL=$?
  ;;
    *)
      echo "Usage: perl-fastcgi {start|stop|restart}"
      exit 1
  ;;
esac      
exit $RETVAL